#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -f *.foam
rm -f *.jpg

# cd tools/atmModelsParante/BoundaryLayer; wclean libso;  cd ../../..;
# cd tools/atmModelsParante/TurbulenceModels; wclean libso;  cd ../../..;
# cd tools/atmModelsParante/WallFunctions; wclean libso;  cd ../../..;

#------------------------------------------------------------------------------
